### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by brooksc** [berkaygediz/RichSpan#1]
**Describe the bug**
I've followed the instructions in the readme to install and run RichSpan and it crashed upon each execution.  

**To Reproduce**
Cloned repo
Created a virtual environment with poetry
pip install -r requirements.txt
pyinstaller --noconfirm --onefile --windowed --icon ".\richspan_icon.ico" --name "RichSpan" --clean --optimize "2" "RichSpan.py"
python RichSpan.py

Crashed.  This is on macos 15.2 Beta (24C5089c) with M2 Macbook Air.  

**Desktop (please complete the following information):**
 Darwin Mac 24.2.0 Darwin Kernel Version 24.2.0: Fri Nov 15 18:54:53 PST 2024; root:xnu-11215.61.2.501.1~1/RELEASE_ARM64_T8112 arm64

**Additional context**

I tried running through the suggesitons @ https://chatgpt.com/share/67500b19-28d8-8000-813c-00bc242d6739 and none were successful.  Below is the full crash report.  

(removing crash report due to length constraint, see above chatgpt that includes crash report details)

**Comment by berkaygediz** [comment]
Thank you for reporting the issue.

The documentation is generally tailored for Windows/Linux devices, so some specific settings are required for ARM, such as specifying the architecture and bundle identifier.

**ARM64:**
```bash
pyinstaller --noconfirm --onefile --windowed --icon "./richspan_icon.ico" --name "RichSpan" --clean --optimize "2" --target-architecture arm64 --osx-bundle-identifier com.berkaygediz.richspan RichSpan.py
```

macOS-specific PyInstaller options: https://pyinstaller.org/en/v6.11.1/usage.html#mac-os-specific-options
PyTorch with the Metal API: https://developer.apple.com/metal/pytorch/

If the issue persists, you can continue with the version of RichSpan.py where the AI functions are disabled. Currently, the latest commits of RichSpan include CUDA-heavy fixes. When running with CPU usage, the `llama-cpp-python` library may encounter module loading errors and cause the executable to stop working.

The version of RichSpan.py with AI functions disabled: https://gofile.io/d/1fremm (10 days)
